### ISSUE TITLE
Can I add this to version 19.07.1

### ISSUE THREAD

**Issue by baalwy** [tano-systems/luci-app-lldpd#1]
Can I add this to version 19.07.1
And how do it
Please because I really needed

**Comment by namedun** [comment]
We don't have Makefiles to build packages for any official OpenWrt releases. But you can try to add this application manually to a device with running OpenWrt by modifying the file system of the device, for example through SSH (scp). I didn't test it for 19.07.1, but I think it's possible.

1. Install default lldpd package by `opkg install lldpd` command on your OpenWrt device.
2. Manually replace `/etc/init.d/lldpd` init script by [this](https://github.com/tano-systems/meta-tanowrt/blob/master/meta-tanowrt/recipes-networking/lldpd/lldpd/files/lldpd.init) file.
3. Manually replace `/etc/config/lldpd` config by [this](https://github.com/tano-systems/meta-tanowrt/blob/master/meta-tanowrt/recipes-networking/lldpd/lldpd/files/lldpd.config) file.
4. Place the contents of the `htdocs` directory of this repository to the `/www` directory of your OpenWrt system.
5. Place the contents of the `luasrc` directory of this repository to the `/usr/lib/lua/luci` directory of your OpenWrt system.
6. Restart (reboot) your OpenWrt device.

**Comment by baalwy** [comment]
Thanks a lot I will try 😘😘😘😘

**Comment by marek22k** [comment]
I have tried to apply these improvements. They worked for me. I only had to change the username of the chmod from `lldpd` to `lldp`.
https://github.com/openwrt/openwrt/pull/13018
